name: Create release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mkisofs

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull all submodules
        run: |
          git submodule update --init --recursive

      - name: Uncompress Basic-Forensic-Analysis-using-Autopsy-Lab/src/image_zero.tar.gz
        run: |
          tar -xvf Basic-Forensic-Analysis-using-Autopsy-Lab/src/image_zero.tar.gz -C Basic-Forensic-Analysis-using-Autopsy-Lab/src/
          rm Basic-Forensic-Analysis-using-Autopsy-Lab/src/image_zero.tar.gz

      - name: Create Android-Forensics-Lab.iso
        run: |
          dd if=/dev/zero of=Android-Forensics-Lab.iso bs=512 count=200000
          mkisofs -o Android-Forensics-Lab.iso Android-Forensics-Lab/src/

      - name: Create Anti-Forensics-Techniques-Lab.iso
        run: |
          dd if=/dev/zero of=Android-Forensics-Lab.iso bs=512 count=200000
          mkisofs -o Android-Forensics-Lab.iso Android-Forensics-Lab/src/

      - name: Create Basic-Data-Hiding-Techniques-Lab.iso
        run: |
          dd if=/dev/zero of=Android-Forensics-Lab.iso bs=512 count=200000
          mkisofs -o Android-Forensics-Lab.iso Android-Forensics-Lab/src/

      - name: Create Basic-Forensic-Analysis-using-Autopsy-Lab.iso
        run: |
          dd if=/dev/zero of=Android-Forensics-Lab.iso bs=512 count=1171875
          mkisofs -o Android-Forensics-Lab.iso Android-Forensics-Lab/src/

      - name: Create Data-Acquisition-Using-dd-Lab.iso
        run: |
          dd if=/dev/zero of=Android-Forensics-Lab.iso bs=512 count=200000
          mkisofs -o Android-Forensics-Lab.iso Android-Forensics-Lab/src/

      - name: Create Developing-Your-Own-Image-Steganography-Tool-Lab.iso
        run: |
          dd if=/dev/zero of=Android-Forensics-Lab.iso bs=512 count=200000
          mkisofs -o Android-Forensics-Lab.iso Android-Forensics-Lab/src/

      - name: Create Drone-Forensics-Lab.iso
        run: |
          dd if=/dev/zero of=Android-Forensics-Lab.iso bs=512 count=200000
          mkisofs -o Android-Forensics-Lab.iso Android-Forensics-Lab/src/

      - name: Create Examine-Windows-NTFS-using-WinHex-Lab.iso
        run: |
          dd if=/dev/zero of=Android-Forensics-Lab.iso bs=512 count=200000
          mkisofs -o Android-Forensics-Lab.iso Android-Forensics-Lab/src/

      - name: Create File-Carving-Lab.iso
        run: |
          dd if=/dev/zero of=Android-Forensics-Lab.iso bs=512 count=200000
          mkisofs -o Android-Forensics-Lab.iso Android-Forensics-Lab/src/

      - name: Create Forensics-on-Discord-Lab.iso
        run: |
          dd if=/dev/zero of=Android-Forensics-Lab.iso bs=512 count=200000
          mkisofs -o Android-Forensics-Lab.iso Android-Forensics-Lab/src/

      - name: Create Memory-Forensics-Lab.iso
        run: |
          dd if=/dev/zero of=Android-Forensics-Lab.iso bs=512 count=200000
          mkisofs -o Android-Forensics-Lab.iso Android-Forensics-Lab/src/

      - name: Create Network-Forensics-with-Xplico-Lab.iso
        run: |
          dd if=/dev/zero of=Android-Forensics-Lab.iso bs=512 count=200000
          mkisofs -o Android-Forensics-Lab.iso Android-Forensics-Lab/src/

      - name: Create Reverse-Engineering-Ghidra-Lab.iso
        run: |
          dd if=/dev/zero of=Android-Forensics-Lab.iso bs=512 count=200000
          mkisofs -o Android-Forensics-Lab.iso Android-Forensics-Lab/src/

      - name: Create Reverse-Engineering-IDA-Lab.iso
        run: |
          dd if=/dev/zero of=Android-Forensics-Lab.iso bs=512 count=200000
          mkisofs -o Android-Forensics-Lab.iso Android-Forensics-Lab/src/

      - name: Create Steganography-with-Audio-File-Lab.iso
        run: |
          dd if=/dev/zero of=Android-Forensics-Lab.iso bs=512 count=200000
          mkisofs -o Android-Forensics-Lab.iso Android-Forensics-Lab/src/

      - name: Create Steganography-with-Image-File-Lab.iso
        run: |
          dd if=/dev/zero of=Android-Forensics-Lab.iso bs=512 count=200000
          mkisofs -o Android-Forensics-Lab.iso Android-Forensics-Lab/src/

      - name: Create Windows-Data-Acquisition-Lab.iso
        run: |
          dd if=/dev/zero of=Android-Forensics-Lab.iso bs=512 count=200000
          mkisofs -o Android-Forensics-Lab.iso Android-Forensics-Lab/src/

      - name: Create One Release with all the ISOs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
            --title "$tag" \
            --notes "Release $tag" \
          Android-Forensics-Lab.iso \
          Anti-Forensics-Techniques-Lab.iso \
          Basic-Data-Hiding-Techniques-Lab.iso \
          Basic-Forensic-Analysis-using-Autopsy-Lab.iso \
          Data-Acquisition-Using-dd-Lab.iso \
          Developing-Your-Own-Image-Steganography-Tool-Lab.iso \
          Drone-Forensics-Lab.iso \
          Examine-Windows-NTFS-using-WinHex-Lab.iso \
          File-Carving-Lab.iso \
          Forensics-on-Discord-Lab.iso \
          Memory-Forensics-Lab.iso \
          Network-Forensics-with-Xplico-Lab.iso \
          Reverse-Engineering-Ghidra-Lab.iso \
          Reverse-Engineering-IDA-Lab.iso \
          Steganography-with-Audio-File-Lab.iso \
          Steganography-with-Image-File-Lab.iso \
          Windows-Data-Acquisition-Lab.iso
